In [1]:
import numpy as np

In [2]:
# 1D array
a = np.array([1, 2, 3])

# 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])

# Zeros, Ones
zeros = np.zeros((2, 3))
ones = np.ones((3, 3))

# Range
arr = np.arange(0, 10, 2)

# Evenly spaced numbers
lin = np.linspace(0, 1, 5)

In [4]:
print(a.shape)     # dimensions
print(a.size)     # number of elements
print(a.dtype)     # data type

(3,)
3
int32


In [5]:
a = np.array([1, 2, 3])

a + 2
a * 3
np.sqrt(a)
np.mean(a)
np.sum(a)
np.max(a)
np.min(a)

1

In [6]:
a = np.array([1, 2, 3, 4, 5])

a[0]        # first element
a[-1]       # last element
a[1:4]      # slicing

array([2, 3, 4])

In [7]:
b = np.array([[1, 2], [3, 4]])

b[0, 1]     # element at row 0, col 1
b[:, 1]     # all rows, second column

array([2, 4])

In [8]:
a = np.arange(6)

a.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
np.random.rand(3)          # random floats
np.random.randint(1, 10, 5) # random integers

array([1, 3, 8, 2, 1])

In [10]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

np.dot(a, b)      # matrix multiplication
a.T               # transpose
np.linalg.inv(a)  # inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [11]:
np.concatenate([a, b])
np.vstack([a, b])
np.hstack([a, b])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [12]:
a = np.array([1, 2, 3, 4, 5])

# Create empty array
e = np.empty((2, 3))

# Identity matrix
i = np.eye(3)

# Diagonal matrix
d = np.diag([1, 2, 3])

# Full array
f = np.full((2, 2), 7)

In [14]:
print(e)
print(i)
print(d)
print(f)

[[1.06788918e-287 2.50521240e-292 3.00719473e-273]
 [1.29196797e-263 5.55062520e-254 7.82850172e-249]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[7 7]
 [7 7]]


In [15]:
arr = np.array([10, 20, 30, 40, 50])

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.max(arr))
print(np.min(arr))
print(np.argmax(arr))
print(np.argmin(arr))

30.0
30.0
14.142135623730951
200.0
50
10
4
0


In [16]:
arr = np.array([5, 2, 8, 1, 9])

print(np.sort(arr))

[1 2 5 8 9]


In [17]:
a = np.array([[3, 1], [4, 2]])

print(np.sort(a, axis=0))
print(np.sort(a, axis=1))

[[3 1]
 [4 2]]
[[1 3]
 [2 4]]


In [18]:
arr = np.array([10, 15, 20, 25, 30])

print(arr[arr > 20])
print(arr[arr % 2 == 0])

[25 30]
[10 20 30]


In [19]:
a = np.array([1, 2, 3])

print(a + 10)
print(a * 5)

[11 12 13]
[ 5 10 15]


In [20]:
a = np.array([1, 2, 3])

print(a + 10)
print(a * 5)

[11 12 13]
[ 5 10 15]
